apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-dashboard
  labels:
    app: risk-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: risk-dashboard
  template:
    metadata:
      labels:
        app: risk-dashboard
    spec:
      containers:
        - name: risk-dashboard
          image: ghcr.io/grosfish69/risk-dashboard:0.1.0
          ports:
            - containerPort: 8000